
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'user_management'
      MYSQL_USER: 'Admin'
      MYSQL_PASSWORD: '1234'
      TZ: Europe/Rome
    command: --init-file /data/application/init.sql
    volumes:
        - mysql_data:/var/lib/mysql
        - ./init.sql:/data/application/init.sql
    ports:
        - 3307:3306
    networks:
        - services_network
  datacollector:
    image: datacollector_image
    build:
      context: ./data_collector
      dockerfile: datacollectorDockerfile
    container_name: datacollector
    depends_on:
        - mysql
    networks:
        - services_network

  servergrpc:
    image: servergrpc_image
    build:
      context: ./servergRPC
      dockerfile: servergRPCDockerfile
    container_name: servergRPC
    depends_on:
       - datacollector
    ports:
       - "50051:50051"
    networks:
        - services_network

networks:
  services_network:
    driver: bridge

volumes:
  mysql_data: {}
