services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usermanagement
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  bash_runner:
    build:
      context: .
      dockerfile: bashDockerfile
    depends_on:
      mysql:
         condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usermanagement

  datacollector:
    image: datacollector_image
    build:
      context: ./data_collector
      dockerfile: datacollectorDockerfile
    container_name: datacollector
    depends_on:
      mysql:
         condition: service_healthy

  servergrpc:
    image: servergrpc_image
    build:
      context: ./servergRPC
      dockerfile: servergRPCDockerfile
    container_name: servergRPC
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    ports:
       - "50051:50051"
 
volumes:
  mysql_data:
