CREATE DATABASE IF NOT EXISTS user_management;

USE user_management;

CREATE TABLE IF NOT EXISTS users(
    email VARCHAR(255) PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL);

CREATE TABLE IF NOT EXISTS stock_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255),
    ticker VARCHAR(10),
    value DOUBLE NOT NULL,
    timestamp DATETIME NOT NULL,
    FOREIGN KEY (email) REFERENCES users(email));

CREATE USER IF NOT EXISTS 'Admin'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON user_management TO 'Admin'@'%';

FLUSH PRIVILEGES;
